<select name="bankCode" id="bankCode">
    <option value="">Selecione um banco</option>
    <option value="341">Itaú</option>
    <option value="237">Bradesco</option>
    <option value="104">Caixa</option>
    <option value="033">Santander</option>
    <option value="001">Banco do Brasil</option>
    <option value="260">Nubank</option>
    <option value="208">BTG Pactual</option>
    <option value="748">Sicredi</option>
    <option value="756">Sicoob</option>
    <option value="041">Banrisul</option>
    <option value="323">Mercado Pago</option>
    <option value="318">Banco BMG</option>
    <option value="136">Unicred</option>
    <option value="348">XP Banking</option>
    <option value="237">Next</option>
    <option value="380">PicPay</option>
    <option value="623">Banco PAN</option>
    <option value="335">Banco Digio</option>
    <option value="004">Banco do Nordeste do Brasil</option>
    <option value="335">Uber Conta by Digio</option>
    <option value="748">Woop</option>
    <option value="422">Safra</option>
    <option value="611">Banco Paulista</option>
    <option value="422">SafraPay</option>
    <option value="745">Citi</option>
    <option value="422">Safra Financeira</option>
    <option value="637">Banco Sofisa</option>
    <option value="655">Banco BV</option>
    <option value="000">Méliuz</option>
    <option value="000">InfinitePay</option>
    <option value="104">Caixa Tem</option>
    <option value="208">Necton</option>
    <option value="301">RecargaPay</option>
    <option value="197">Stone Pagamentos</option>
    <option value="184">Itaú BBA</option>
    <option value="724">Porto Bank</option>
    <option value="536">Neon</option>
    <option value="000">Rede Celcoin</option>
    <option value="000">PagueVeloz (Serasa)</option>
    <option value="341">Itaú Empresas</option>
    <option value="336">C6 Bank</option>
    <option value="290">PagBank</option>
    <option value="077">Inter</option>
    <option value="000">Midway</option>
    <option value="070">Banco BRB</option>
    <option value="389">Banco Mercantil</option>
</select>
