<?php

return [
    'secret' => env('ASSISTANT_WEBHOOK_SECRET'),
    'secret_header' => env('ASSISTANT_WEBHOOK_SECRET_HEADER', 'X-Assistant-Secret'),
    'recent_transactions_limit' => (int) env('ASSISTANT_RECENT_TRANSACTIONS_LIMIT', 8),
    'phone' => [
        'default_country_code' => env('PHONE_DEFAULT_COUNTRY_CODE', '55'),
    ],
    'intents' => [
        'create_transaction',
        'create_budget',
        'get_balance',
        'get_budget_status',
        'list_recent_transactions',
    ],
    'categories' => [
        'income' => [
            'Salary',
            'Business',
            'Commission',
            'Allowance',
            'Saving',
            'Investment',
            'Pension',
            'Rent',
            'Transport',
            'Freelance',
            'Gift received',
            'Loan received',
            'Pocket money',
            'Tutoring',
            'Other',
        ],
        'expense' => [
            'Personal',
            'Food & drink',
            'Grocery',
            'Travel',
            'Entertainment',
            'Fuel',
            'Bill',
            'Medical',
            'Transport',
            'Education',
            'Home',
            'Loan paid',
            'Shopping',
            'Office',
            'Rent paid',
            'Donation',
            'Gifts',
            'Fitness',
            'Mobile',
            'Insurance',
            'Family',
            'Wedding',
            'Electronics',
            'Committee',
            'Installments',
            'Sports',
            'Other',
        ],
        'budget' => [
            'Personal',
            'Food & drink',
            'Grocery',
            'Travel',
            'Entertainment',
            'Fuel',
            'Bill',
            'Medical',
            'Transport',
            'Education',
            'Home',
            'Loan paid',
            'Shopping',
            'Office',
            'Rent paid',
            'Donation',
            'Gifts',
            'Fitness',
            'Mobile',
            'Insurance',
            'Family',
            'Wedding',
            'Electronics',
            'Committee',
            'Installments',
            'Sports',
            'Salary',
            'Business',
            'Commission',
            'Allowance',
            'Saving',
            'Investment',
            'Pension',
            'Rent',
            'Freelance',
            'Gift received',
            'Loan received',
            'Pocket money',
            'Tutoring',
            'Other',
        ],
    ],
];
